name: pdf_viewer
description: A Flutter plugin for handling PDF files. Works on both Android & iOS.
version: 2.0.0
homepage: https://github.com/geniusrestore/pdf_viewer

environment:
  sdk: ">=2.19.5 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.1.1
  numberpicker: ^2.1.1
  path_provider: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
